In [1]:
import pandas as pd 
import numpy as np

In [2]:
train_df = pd.read_csv("Training.csv")
test_df = pd.read_csv("Testing.csv")

df = pd.concat([train_df , test_df] , axis=0)
df.head(1)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  scurring  \
0       0           0             0        0                 0  ...         0   

   skin_peeling  silver_like_dusting  small_dents_in_nails  \
0             0                    0                     0   

   inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                   0        0                     0                  0   

          prognosis  Unnamed: 133  
0  Fungal infection           NaN  

[1 rows x 134 columns]

In [3]:
df = df.drop(["Unnamed: 133"] , axis=1)

In [4]:
df.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4962.000000  4962.000000           4962.000000          4962.000000   
mean      0.138049     0.160016              0.021967             0.045143   
std       0.344986     0.366658              0.146590             0.207639   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4962.000000  4962.000000  4962.000000   4962.000000  4962.000000   
mean      0.021967     0.162233     0.139057      0.045143     0.045143   
std       0.146590     0.368702     0.346041      0.207639     0.207639   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4962.000000  ...         4962.000000  4962.000000  4962.000000   
mean           0.021967  ...            0.021967     0.021967     0.021967   
std            0.146590  ...            0.146590     0.146590     0.146590   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4962.000000          4962.000000           4962.000000   
mean       0.023378             0.023176              0.023176   
std        0.151115             0.150478              0.150478   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4962.000000  4962.000000           4962.000000   
mean             0.023176     0.023176              0.023378   
std              0.150478     0.150478              0.151115   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4962.000000  
mean            0.023176  
std             0.150478  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [5]:
df.isna().sum() 

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [6]:
df = df.dropna() 

In [7]:
df["prognosis"].unique().size

41

In [8]:
print(df["prognosis"].unique())

['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis' 'Drug Reaction'
 'Peptic ulcer diseae' 'AIDS' 'Diabetes ' 'Gastroenteritis'
 'Bronchial Asthma' 'Hypertension ' 'Migraine' 'Cervical spondylosis'
 'Paralysis (brain hemorrhage)' 'Jaundice' 'Malaria' 'Chicken pox'
 'Dengue' 'Typhoid' 'hepatitis A' 'Hepatitis B' 'Hepatitis C'
 'Hepatitis D' 'Hepatitis E' 'Alcoholic hepatitis' 'Tuberculosis'
 'Common Cold' 'Pneumonia' 'Dimorphic hemmorhoids(piles)' 'Heart attack'
 'Varicose veins' 'Hypothyroidism' 'Hyperthyroidism' 'Hypoglycemia'
 'Osteoarthristis' 'Arthritis' '(vertigo) Paroymsal  Positional Vertigo'
 'Acne' 'Urinary tract infection' 'Psoriasis' 'Impetigo']


In [9]:
import re
def replace_space(x) : 
    return re.sub(r'\(.*?\)' , '' , x).strip().lstrip().rstrip().replace(" " , "_")
df["prognosis"] = df["prognosis"].apply(replace_space)
print(df["prognosis"].unique())

['Fungal_infection' 'Allergy' 'GERD' 'Chronic_cholestasis' 'Drug_Reaction'
 'Peptic_ulcer_diseae' 'AIDS' 'Diabetes' 'Gastroenteritis'
 'Bronchial_Asthma' 'Hypertension' 'Migraine' 'Cervical_spondylosis'
 'Paralysis' 'Jaundice' 'Malaria' 'Chicken_pox' 'Dengue' 'Typhoid'
 'hepatitis_A' 'Hepatitis_B' 'Hepatitis_C' 'Hepatitis_D' 'Hepatitis_E'
 'Alcoholic_hepatitis' 'Tuberculosis' 'Common_Cold' 'Pneumonia'
 'Dimorphic_hemmorhoids' 'Heart_attack' 'Varicose_veins' 'Hypothyroidism'
 'Hyperthyroidism' 'Hypoglycemia' 'Osteoarthristis' 'Arthritis'
 'Paroymsal__Positional_Vertigo' 'Acne' 'Urinary_tract_infection'
 'Psoriasis' 'Impetigo']


In [10]:
from sklearn.feature_extraction.text import CountVectorizer 

vectorizer = CountVectorizer()
result = vectorizer.fit_transform(df["prognosis"]) 
print(vectorizer.get_feature_names_out())
labels = pd.DataFrame( result.toarray() , columns=vectorizer.get_feature_names_out() )
labels.head()

['acne' 'aids' 'alcoholic_hepatitis' 'allergy' 'arthritis'
 'bronchial_asthma' 'cervical_spondylosis' 'chicken_pox'
 'chronic_cholestasis' 'common_cold' 'dengue' 'diabetes'
 'dimorphic_hemmorhoids' 'drug_reaction' 'fungal_infection'
 'gastroenteritis' 'gerd' 'heart_attack' 'hepatitis_a' 'hepatitis_b'
 'hepatitis_c' 'hepatitis_d' 'hepatitis_e' 'hypertension'
 'hyperthyroidism' 'hypoglycemia' 'hypothyroidism' 'impetigo' 'jaundice'
 'malaria' 'migraine' 'osteoarthristis' 'paralysis'
 'paroymsal__positional_vertigo' 'peptic_ulcer_diseae' 'pneumonia'
 'psoriasis' 'tuberculosis' 'typhoid' 'urinary_tract_infection'
 'varicose_veins']


acne  aids  alcoholic_hepatitis  allergy  arthritis  bronchial_asthma  \
0     0     0                    0        0          0                 0   
1     0     0                    0        0          0                 0   
2     0     0                    0        0          0                 0   
3     0     0                    0        0          0                 0   
4     0     0                    0        0          0                 0   

   cervical_spondylosis  chicken_pox  chronic_cholestasis  common_cold  ...  \
0                     0            0                    0            0  ...   
1                     0            0                    0            0  ...   
2                     0            0                    0            0  ...   
3                     0            0                    0            0  ...   
4                     0            0                    0            0  ...   

   osteoarthristis  paralysis  paroymsal__positional_vertigo  \
0                0          0                              0   
1                0          0                              0   
2                0          0                              0   
3                0          0                              0   
4                0          0                              0   

   peptic_ulcer_diseae  pneumonia  psoriasis  tuberculosis  typhoid  \
0                    0          0          0             0        0   
1                    0          0          0             0        0   
2                    0          0          0             0        0   
3                    0          0          0             0        0   
4                    0          0          0             0        0   

   urinary_tract_infection  varicose_veins  
0                        0               0  
1                        0               0  
2                        0               0  
3                        0               0  
4                        0               0  

[5 rows x 41 columns]

In [11]:
labels.shape

(4962, 41)

In [12]:
df = df.drop(["prognosis"] , axis = 1 )

In [13]:
from sklearn.model_selection import train_test_split 

x_train , x_test , y_train , y_test = train_test_split(df , labels , test_size=0.1 , random_state=0)

In [14]:
print("the shape of x_train is" , x_train.shape) 
print("the shape of y_train is" , y_train.shape) 
print("the shape of x_test is" , x_test.shape) 
print("the shape of y_test is" , y_test.shape) 

the shape of x_train is (4465, 132)
the shape of y_train is (4465, 41)
the shape of x_test is (497, 132)
the shape of y_test is (497, 41)


In [15]:
print(y_test.values)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
from keras.models import Sequential
from keras.layers import Dense , Input , Dropout
from keras.optimizers import SGD , Adam

model = Sequential()
model.add(Input(shape=(x_train.shape[1],)))
model.add(Dense(150, activation="relu"))
model.add(Dropout(0.3))  # 30% of the neurons will be randomly dropped
model.add(Dense(100, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(90, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(y_train.shape[1], activation="sigmoid"))

model.summary()

# Compile the Model
model.compile(
    optimizer=Adam(learning_rate=0.0001),  # Change optimizer to Adam and adjust learning rate
    loss="binary_crossentropy",
    metrics=["accuracy"]
)
model.fit(x_train.values 
, y_train.values 
, epochs=100 
, batch_size=32
, validation_split=0.2)



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 150)               19950     
                                                                 
 dropout (Dropout)           (None, 150)               0         
                                                                 
 dense_1 (Dense)             (None, 100)               15100     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_2 (Dense)             (None, 90)                9090      
                                                                 
 dropout_2 (Dropout)         (None, 90)                0         
                                                                 
 dense_3 (Dense)             (None, 41)               

In [17]:
model.evaluate(x_test.values , y_test.values)

16/16 [==============================] - 0s 5ms/step - loss: 1.9133e-05 - accuracy: 1.0000


[1.9133138266624883e-05, 1.0]

In [18]:
res = model.predict(x_test.values)
print("data" , x_test.values[0])
print("result" , vectorizer.get_feature_names_out()[res[0].argmax()])


16/16 [==============================] - 0s 2ms/step
data [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
result impetigo


In [19]:
new_row = {col : 0 for col in x_train.columns } 
print(new_row)
for i , value in enumerate( x_test.values[0] ):
    if value == 1 :
        new_row[x_train.columns[i]] = 1 

{'itching': 0, 'skin_rash': 0, 'nodal_skin_eruptions': 0, 'continuous_sneezing': 0, 'shivering': 0, 'chills': 0, 'joint_pain': 0, 'stomach_pain': 0, 'acidity': 0, 'ulcers_on_tongue': 0, 'muscle_wasting': 0, 'vomiting': 0, 'burning_micturition': 0, 'spotting_ urination': 0, 'fatigue': 0, 'weight_gain': 0, 'anxiety': 0, 'cold_hands_and_feets': 0, 'mood_swings': 0, 'weight_loss': 0, 'restlessness': 0, 'lethargy': 0, 'patches_in_throat': 0, 'irregular_sugar_level': 0, 'cough': 0, 'high_fever': 0, 'sunken_eyes': 0, 'breathlessness': 0, 'sweating': 0, 'dehydration': 0, 'indigestion': 0, 'headache': 0, 'yellowish_skin': 0, 'dark_urine': 0, 'nausea': 0, 'loss_of_appetite': 0, 'pain_behind_the_eyes': 0, 'back_pain': 0, 'constipation': 0, 'abdominal_pain': 0, 'diarrhoea': 0, 'mild_fever': 0, 'yellow_urine': 0, 'yellowing_of_eyes': 0, 'acute_liver_failure': 0, 'fluid_overload': 0, 'swelling_of_stomach': 0, 'swelled_lymph_nodes': 0, 'malaise': 0, 'blurred_and_distorted_vision': 0, 'phlegm': 0, 'th

In [21]:
model.save("disease_model.h5")

c:\Users\fujitsu\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [32]:
from keras.models import load_model 
print(x_test.values[0].reshape(1 , -1).shape)
print(load_model("disease_model.h5").predict(x_test.values[0].reshape(1 , -1))[0].argmax())

(1, 132)
1/1 [==============================] - 1s 881ms/step
27
